src/com/labs247/telyu/bean/mapreduce/Client.java
package com.labs247.telyu.bean.mapreduce;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.ejb.Schedule;

import javax.ejb.Singleton;
import javax.ejb.Startup;
//import javax.ejb.Stateful;

import org.jboss.logging.Logger;

import com.labs247.telyu.model.mapreduce.Configuration;
import com.labs247.telyu.model.mapreduce.Item;
import com.labs247.telyu.model.mapreduce.Mapreduce;
import com.labs247.telyu.model.mapreduce.Properties;
import com.labs247.telyu.bean.mapreduce.Client;

//@Stateful
@Singleton
@Startup
public class Client {

	public enum States {
		BEFORESTARTED, STARTED, PAUSED, SHUTTINGDOWN
	};

	private States state;
	private Configuration configuration;

	static String host = "192.168.3.132";
	static String port = "8080";
	static Mapreduce mapreduce = null;
	static long fire_time = System.currentTimeMillis();
	static Logger logger = Logger.getLogger(Client.class);

	public Client() {

	}

	@PostConstruct
	public void initialize() {
		logger.info("............................................................");
		System.out.println("............................................................");
		state = States.BEFORESTARTED;
		// Perform intialization
		get_de_data();
		state = States.STARTED;
	}

	// fire every 5 minut

	// @Schedule(second = "*/5", minute = "*", hour = "*", persistent = false)
	@Schedule(minute = "*/5", hour = "*", persistent = false)
	public void atSchedule() throws InterruptedException {

		get_de_data();

		System.out.println("DeclarativeScheduler:: In atSchedule() fired get_jmxdata()");

	}

	public void get_de_data() {

		try {
			System.out.println(".......................Rest Dimulai ..................................");
			RestClient _client = new RestClient(host, port);
			String URL = "http://192.168.3.132:8080/api/v1/clusters/C10H16/configurations/service_config_versions/?service_name=MAPREDUCE2";

			fire_time = System.currentTimeMillis();
			String json = _client.basic_auth_client(URL);

			mapreduce = Parsing.json2DataNode(json);

			System.out.println("..........................MAPREDUCE Data : ...................");
//			System.out.println(getPropertiesData());

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@PreDestroy
	public void terminate() {
		state = States.SHUTTINGDOWN;
		// Perform termination
		System.out.println("JMXRestClient shutdown in progress");
	}

	public States getState() {
		return state;
	}

	public void setState(States state) {
		this.state = state;
	}

	public long getFiretime() {
		return fire_time;
	}

	public String getHref() {
		return mapreduce.getHref();
	}

	public Item getItemData() {

		// i.e java.lang:type=OperatingSystem

		Item _de_bean = mapreduce.getItems().stream().filter(item -> "C10H16".equals(item.getClusterName())).findAny()
				.orElse(null);
		return _de_bean;
	}

	public Configuration getConfigMapEnv() {

		Item _de_bean = mapreduce.getItems().stream().filter(item -> "C10H16".equals(item.getClusterName())).findAny()
				.orElse(null);

		configuration = _de_bean.getConfigurations().stream().filter(config -> "mapred-env".equals(config.getType()))
				.findAny().orElse(null);
		return configuration;
	}
	
	public Configuration getConfigMapSite() {

		Item _de_bean = mapreduce.getItems().stream().filter(item -> "C10H16".equals(item.getClusterName())).findAny()
				.orElse(null);

		configuration = _de_bean.getConfigurations().stream().filter(config -> "mapred-site".equals(config.getType()))
				.findAny().orElse(null);
		return configuration;
	}

	public Properties getMapredEnv() {
		Item _de_bean = mapreduce.getItems().stream().filter(item -> "C10H16".equals(item.getClusterName())).findAny()
				.orElse(null);

		configuration = _de_bean.getConfigurations().stream().filter(config -> "mapred-env".equals(config.getType()))
				.findAny().orElse(null);

		return configuration.getProperties();
	}
	
	public Properties getMapredSite() {
		Item _de_bean = mapreduce.getItems().stream().filter(item -> "C10H16".equals(item.getClusterName())).findAny()
				.orElse(null);

		configuration = _de_bean.getConfigurations().stream().filter(config -> "mapred-site".equals(config.getType()))
				.findAny().orElse(null);

		return configuration.getProperties();
	}

}

src/com/labs247/telyu/bean/mapreduce/DataViewMAP.java
package com.labs247.telyu.bean.mapreduce;

import com.labs247.telyu.bean.mapreduce.Client;

import java.io.Serializable;

import javax.annotation.PostConstruct;
//import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class DataViewMAP implements Serializable{
	
	String jobsize, mapred, history, logDir, pid, nofile, nproc, content, mapchild,reducechild, adminuser, max,
	classpath, framework, acls, admin, fname, modifyjob, viewjob, counter, timeline, queue, slow, acl, bindhost,
	done, policy, inter, recovery, store, enable, jobre, webapp, javaopts, loglevel, outcom, spill, speculative, compress,
	comtype, buffer, javasize, reenable, rein, retime, bpercent, mpercent, shuffel, spec, port, sort, timeout, command,
	appcommand, amlog, amstaging;
	
//	@EJB Client c;
	Client c = new Client();
	
	 @PostConstruct
	    public void init() {
		c.get_de_data(); 
		mapred = c.getMapredEnv().getMapredUserNprocLimit();
		jobsize = c.getMapredEnv().getJobhistoryHeapsize();
		logDir = c.getMapredEnv().getMapredLogDirPrefix();
		pid = c.getMapredEnv().getMapredPidDirPrefix();
		nofile = c.getMapredEnv().getMapredUserNofileLimit();
		nproc = c.getMapredEnv().getMapredUserNprocLimit();
		content = c.getMapredEnv().getContent();
		
		history = c.getMapredSite().getMapreduceJobhistoryAddress();
		mapchild = c.getMapredSite().getMapreduceAdminMapChildJavaOpts();
		reducechild = c.getMapredSite().getMapreduceAdminReduceChildJavaOpts();
		adminuser = c.getMapredSite().getMapreduceAdminUserEnv();
		max = c.getMapredSite().getMapreduceAmMaxAttempts();
		classpath = c.getMapredSite().getMapreduceApplicationClasspath();
		framework = c.getMapredSite().getMapreduceApplicationFrameworkPath();
		acls = c.getMapredSite().getMapreduceClusterAclsEnabled();
		admin = c.getMapredSite().getMapreduceClusterAdministrators();
		fname = c.getMapredSite().getMapreduceFrameworkName();
		modifyjob = c.getMapredSite().getMapreduceJobAclModifyJob();
		viewjob = c.getMapredSite().getMapreduceJobAclViewJob();
		counter = c.getMapredSite().getMapreduceJobCountersMax();
		timeline = c.getMapredSite().getMapreduceJobEmitTimelineData();
		queue = c.getMapredSite().getMapreduceJobQueuename();
		slow = c.getMapredSite().getMapreduceJobReduceSlowstartCompletedmaps();
		acl = c.getMapredEnv().getMapreduceJobhistoryAdminAcl();
		bindhost = c.getMapredSite().getMapreduceJobhistoryBindHost();
		done = c.getMapredSite().getMapreduceJobhistoryDoneDir();
		policy = c.getMapredSite().getMapreduceJobhistoryHttpPolicy();
		inter = c.getMapredSite().getMapreduceJobhistoryIntermediateDoneDir();
		recovery = c.getMapredSite().getMapreduceJobhistoryRecoveryEnable();
		store = c.getMapredSite().getMapreduceJobhistoryRecoveryStoreClass();
		enable = c.getMapredSite().getMapreduceJobhistoryRecoveryEnable();
		jobre = c.getMapredSite().getMapreduceJobhistoryRecoveryStoreLeveldbPath();
		webapp = c.getMapredSite().getMapreduceJobhistoryWebappAddress();
		javaopts = c.getMapredSite().getMapreduceMapJavaOpts();
		loglevel = c.getMapredSite().getMapreduceMapLogLevel();
		outcom = c.getMapredSite().getMapreduceMapOutputCompress();
		spill = c.getMapredSite().getMapreduceMapSortSpillPercent();
		speculative = c.getMapredSite().getMapreduceMapSpeculative();
		compress = c.getMapredSite().getMapreduceOutputFileoutputformatCompress();
		comtype = c.getMapredSite().getMapreduceOutputFileoutputformatCompressType();
		buffer = c.getMapredSite().getMapreduceReduceInputBufferPercent();
		javasize = c.getMapredSite().getMapreduceReduceJavaOpts();
		reenable = c.getMapredSite().getMapreduceReduceShuffleFetchRetryEnabled();
		rein = c.getMapredSite().getMapreduceReduceShuffleFetchRetryIntervalMs();
		retime = c.getMapredSite().getMapreduceReduceShuffleFetchRetryTimeoutMs();
		bpercent = c.getMapredSite().getMapreduceReduceShuffleInputBufferPercent();
		mpercent = c.getMapredSite().getMapreduceReduceShuffleMergePercent();
		shuffel = c.getMapredSite().getMapreduceReduceShuffleParallelcopies();
		spec = c.getMapredSite().getMapreduceReduceSpeculative();
		port = c.getMapredSite().getMapreduceShufflePort();
		sort = c.getMapredSite().getMapreduceTaskIoSortFactor();
		timeout = c.getMapredSite().getMapreduceTaskTimeout();
		command = c.getMapredSite().getYarnAppMapreduceAmAdminCommandOpts();
		appcommand = c.getMapredSite().getYarnAppMapreduceAmCommandOpts();
		amlog = c.getMapredSite().getYarnAppMapreduceAmLogLevel();
		amstaging = c.getMapredSite().getYarnAppMapreduceAmStagingDir();
	 }
	 
	 public String getJobSize() {
	        return jobsize;
	    }
	 
	 public String getMapred() {
	        return mapred;
	    }
	 
	 public String getHistory() {
	        return history;
	    }
	 
	 public String getLogDir() {
	        return logDir;
	    }
	 
	 public String getPid() {
	        return pid;
	    }
	 
	 public String getNoFile() {
	        return nofile;
	    }
	 
	 public String getNproc() {
	        return nproc;
	    }
	 
	 public String getContent() {
	        return content;
	    }
	 
	 public String getMapChild() {
	        return mapchild;
	    }
	 
	 public String getReduceChild() {
	        return reducechild;
	    }
	 
	 public String getAdminUser() {
	        return adminuser;
	    }
	 
	 public String getMax() {
	        return max;
	    }
	 
	 public String getClasspath() {
	        return classpath;
	    }
	 
	 public String getFramework() {
	        return framework;
	    }
	 
	 public String getACLS() {
	        return acls;
	    }
	 
	 public String getAdmin() {
	        return admin;
	    }
	 
	 public String getFname() {
	        return fname;
	    }
	 
	 public String getModifyJob() {
	        return modifyjob;
	    }
	 
	 public String getViewJob() {
	        return viewjob;
	    }
	 
	 public String getCounter() {
	        return counter;
	    }
	 
	 public String getTimeline() {
	        return timeline;
	    }
	 
	 public String getQueue() {
	        return queue;
	    }
	 
	 public String getSlow() {
	        return slow;
	    }
	 
	 public String getAcl() {
	        return acl;
	    }
	 
	 public String getBindHost() {
	        return bindhost;
	    }
	 
	 public String getDone() {
	        return done;
	    }
	 
	 public String getPolicy() {
	        return policy;
	    }
	 
	 public String getInter() {
	        return inter;
	    }
	 
	 public String getRecovery() {
	        return recovery;
	    }
	 
	 public String getStore() {
	        return store;
	    }
	 
	 public String getEnable() {
	        return enable;
	    }
	 
	 public String getJobRe() {
	        return jobre;
	    }
	 
	 public String getWebapp() {
	        return webapp;
	    }
	 
	 public String getJavaOpts() {
	        return javaopts;
	    }
	 
	 public String getLogLevel() {
	        return loglevel;
	    }
	 
	 public String getOutcom() {
	        return outcom;
	    }
	 
	 public String getSpill() {
	        return spill;
	    }
	 
	 public String getSpeculative() {
	        return speculative;
	    }
	 
	 public String getCompress() {
	        return compress;
	    }
	 
	 public String getComType() {
	        return comtype;
	    }
	 
	 public String getBuffer() {
	        return buffer;
	    }
	 
	 public String getJavaSize() {
	        return javasize;
	    }
	 
	 public String getReEnable() {
	        return reenable;
	    }
	 
	 public String getReIn() {
	        return rein;
	    }
	 
	 public String getReTime() {
	        return retime;
	    }
	 
	 public String getBPercent() {
	        return bpercent;
	    }
	 
	 public String getMPercent() {
	        return mpercent;
	    }
	 
	 public String getShuffel() {
	        return shuffel;
	    }
	 
	 public String getSpec() {
	        return spec;
	    }
	 
	 public String getPort() {
	        return port;
	    }
	 
	 public String getSort() {
	        return sort;
	    }
	 
	 public String getTimeout() {
	        return timeout;
	    }
	 
	 public String getCommand() {
	        return command;
	    }
	 
	 public String getAppCommand() {
	        return appcommand;
	    }
	 
	 public String getAmLog() {
	        return amlog;
	    }
	 
	 public String getAmStaging() {
	        return amstaging;
	    }
}

src/com/labs247/telyu/bean/mapreduce/Parsing.java
package com.labs247.telyu.bean.mapreduce;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.labs247.telyu.model.mapreduce.Mapreduce;

public class Parsing {
	public static Mapreduce json2DataNode(String json) {

		JsonParser parser = new JsonParser();

		Mapreduce _datanode = null;

		JsonElement jsonTree = parser.parse(json);

		if (jsonTree.isJsonObject()) {

			JsonObject jsonObject = jsonTree.getAsJsonObject();

			Gson gson = new Gson();

			_datanode = gson.fromJson(jsonObject, Mapreduce.class);

		}

		return _datanode;
	}

}

src/com/labs247/telyu/bean/mapreduce2/MAPREDUCEView.java
package com.labs247.telyu.bean.mapreduce2;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.logging.Logger;

import com.labs247.telyu.model.mapreduce2.AmbariRestClient;
import com.labs247.telyu.model.mapreduce2.ContohConstants;
import com.labs247.telyu.model.mapreduce2.MAPREDUCEConfig;
import com.labs247.telyu.model.mapreduce2.MAPREDUCEItem;
import com.labs247.telyu.model.mapreduce2.POJOConfigResult;
import com.labs247.telyu.model.mapreduce2.POJOConfigResultUtil;

@Named
@ViewScoped
public class MAPREDUCEView implements Serializable {
	
	static final long serialVersionUID = 1237l;
	
	static Logger logger = Logger.getLogger(MAPREDUCEView.class);
	
	POJOConfigResult _json_as_pojo;
	List<MAPREDUCEItem> items;
	
	static String DEFAULT_USER = ContohConstants.Service.DEFAULT_USER; //"admin";
	static String DEFAULT_PASS = ContohConstants.Service.DEFAULT_PASS; //"admin";
	static String CLUSTER = ContohConstants.Service.DEFAULT_CLUSTER; //"C10H16";//"YAVA30";// "H2SO4";
	static String HOSTNAME = ContohConstants.Service.DEFAULT_HOSTNAME; //"192.168.3.132";//192.168.3.132  192.168.3.221 192.168.3.164
	
	// AMBARI_INFRA_SOLR, AMBARI_METRIC ATLAS HIVE KAFKA MAPREDUCE2
	// PIG RANGER SQOOP YARN, ZOOKEEPER, OOZIE	

	static String DEFAULT_SERVICE = "MAPREDUCE2";
	
	MAPREDUCEItem _current_item ;
	List<MAPREDUCEConfig> _current_configurations;
	MAPREDUCEConfig config;
		
	@PostConstruct
	public  void init()  {
		
		try {
		AmbariRestClient _client  =  new AmbariRestClient(HOSTNAME, CLUSTER);
		  
		 String json =  _client.ambari_configurtion_rest_client (DEFAULT_SERVICE);
		  
		 _json_as_pojo = POJOConfigResultUtil.json2pojo( json);
	
		 items = _json_as_pojo.getItems();    	
		 
		 System.out.println("items = "+ items.size());
		 
		 MAPREDUCEItem _current_item = items.stream()
    			 .filter(item -> item.getIsCurrent())
    			 .findAny()
    			 .orElse(null);
		 
		 _current_configurations = _current_item.getConfigurations();
		 
		 System.out.println("_current_configurations = "+ _current_configurations.size());
		 
		 config = getCurrentConfigurationByType("mapred-site");
		 
		}  catch (Exception e) {
			logger.error(e);
		}
		 		 		
	}
	
	public String   getType() {
	   	
	   	   return config.getType();
	    	   
		}
	
	public String   getTag() {
	   	
	   	   return config.getTag();
	    	   
		}
	
	public Integer   getVersion() {
	   	
	   	   return config.getVersion();
	    	   
		}
	
	public String   getClusterName() {
	   	
	   	   return config.getConfig().getClusterName();
	    	   
		}
	public String   getStackId() {
		
	   	   return config.getConfig().getStackId();
	    	   
		}
	
	public Map<String, Object >  getProperties(String type) {
		
			// String _type = "\"" + type +"\"";
		
		MAPREDUCEConfig cfg = getCurrentConfigurationByType(type);
		
	   	   return cfg.get_Properties();
	    	   
		}
	
	public Map<String, Object >  getProperties() {
	   	
	   	   return config.get_Properties();
	    	   
		}
	
	public Map<String, Object>    getPropertiesAttributes() {
	   	
	   	   return config.get_PropertiesAttributes();
	    	   
		}
	
   private  MAPREDUCEConfig  getCurrentConfigurationByType(String type) {
		
	   String _type = "\"" + type +"\"";
	   
	   MAPREDUCEConfig c  = _current_configurations.stream()
				 .filter(e -> _type.equalsIgnoreCase(e.getType()))
	   			 .findAny()
	   			 .orElse(null);
			
		
		return c;
	}
	
}

src/com/labs247/telyu/model/Hbase/JsonParsingUtil.java
package com.labs247.telyu.model.Hbase;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class JsonParsingUtil {
	
	public static Hbase json2DataNode(String json) {

		JsonParser parser = new JsonParser();
		
		Hbase hbasePojo =  null;

		JsonElement jsonTree = parser.parse(json);
		

		if (jsonTree.isJsonObject()) {

			JsonObject jsonObject = jsonTree.getAsJsonObject();

			Gson gson = new Gson();
			
			hbasePojo = gson.fromJson(jsonObject, Hbase.class);
			
		}

		return hbasePojo ;
	}
}

WebContent/sections/includes/Alerts.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:pe="http://primefaces.org/ui/extensions">
        
	<h:form>

		<h:panelGrid columns="2" cellpadding="0" value="test"
			style="width:100%">

			<div class="ui-g">
				<div class="ui-g-2" style="float: left">
					<h2>Alerts</h2>
				</div>
				<h:panelGrid columns="5" cellpadding="0" value="test"
					style="width:40%;float:right">
					<div class="ui-g-2">
						<h:commandButton id="filterAlert" icon="fa fa-filter Black" value="Submit"/>
						<h:commandButton id="actionsAlert" value="Actions" />
					</div>
					<div class="ui-g">
						<div class="ui-g-12 ui-md-6 ui-lg-2">
							<i class="fa fa-gear" id="bor" style="cursor: pointer"
								title="Background Operation Running" />

						</div>

						<div class="ui-g-12 ui-md-6 ui-lg-2">
							<i class="fa fa-bell" id="notif" style="cursor: pointer"
								title="Notifications" />

						</div>

						<div class="ui-g-12 ui-md-6 ui-lg-2">
							<i class="fa fa-bars" id="view" style="cursor: pointer"
								title="Views" />

						</div>

						<div class="ui-g-12 ui-md-6 ui-lg-6">
							<p:menuButton value="admin" icon="fa fa-user"
								style="width:100%; font-size:10pt">
								<p:menuitem value="Setting" style="font-size:10pt" />
								<p:menuitem value="Manage YAVA" style="font-size:10pt" />
								<p:menuitem value="About" style="font-size:10pt" />
								<p:separator />
								<p:menuitem value="Sign Out" style="font-size:10pt" />
							</p:menuButton>
						</div>
					</div>
				</h:panelGrid>
			</div>
		</h:panelGrid>

		<p:dataTable var="alertsList">
			<p:column headerText="Status">
				<h:outputText/>
			</p:column>
	
			<p:column headerText="Alert Definition Name">
				<h:outputText/>
			</p:column>	
				
			<p:column headerText="Service">	
				<h:outputText/>
			</p:column>
			
			<p:column headerText="Last Status Changed">
				<h:outputText/>
			</p:column>
			
			<p:column headerText="State">
				<h:outputText/>
			</p:column>
		</p:dataTable>
		
	</h:form>

        
</ui:composition>

WebContent/sections/includes/sqoopView.xhtml
<ui:composition xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">
	<!-- EXAMPLE-SOURCE-START -->

	<h:form>
		<p:growl id="message"></p:growl>

		<p:tabView activeIndex="#{tabViewManagedBean.index}">

			<p:tab title="SUMMARY">
				<f:facet name="actions">
					<div class="ui-g">
						<div class="ui-g-12 ui-md-6 ui-lg-2">
							<i class="fa fa-gear" id="bor" style="cursor: pointer"
								title="Background Operation Running" />

						</div>

						<div class="ui-g-12 ui-md-6 ui-lg-2">
							<i class="fa fa-bell" id="notif" style="cursor: pointer"
								title="Notifications" />

						</div>

						<div class="ui-g-12 ui-md-6 ui-lg-2">
							<i class="fa fa-bars" id="view" style="cursor: pointer"
								title="Views" />

						</div>

						<div class="ui-g-12 ui-md-6 ui-lg-6">
							<p:menuButton value="admin" icon="fa fa-user"
								style="width:100%; font-size:10pt">
								<p:menuitem value="Setting" style="font-size:10pt" />
								<p:menuitem value="Manage YAVA" style="font-size:10pt" />
								<p:menuitem value="About" style="font-size:10pt" />
								<p:separator />
								<p:menuitem value="Sign Out" style="font-size:10pt" />
							</p:menuButton>
						</div>
					</div>
				</f:facet>
				<h3>SUMMARY</h3>
				<p:breadCrumb style="font-size:10pt">
					<p:menuitem value="Breadcrumb" />
					<p:menuitem value="Services" />
					<p:menuitem value="Sqoop" />
					<p:menuitem value="Summary" />
				</p:breadCrumb>
				<div class="ui-g">
					<div class="ui-g-12 ui-md-2">Component</div>
					<div class="ui-g-12 ui-md-10 ui-g-nopad">
						<div class="ui-g-12 ui-g-nopad">
							<div class="ui-g">
								<div class="ui-g-12 ui-md-4">
									<div>
										<p:outputLabel value="3 Installed"></p:outputLabel>
									</div>
									<div>
										<p:outputLabel value="Sqoop Clients"></p:outputLabel>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</p:tab>
			<p:tab title="CONFIGS">
				<f:facet name="actions">
					<div class="ui-g">
						<div class="ui-g-12 ui-md-6 ui-lg-2">
							<i class="fa fa-gear" id="bor" style="cursor: pointer"
								title="Background Operation Running" />

						</div>

						<div class="ui-g-12 ui-md-6 ui-lg-2">
							<i class="fa fa-bell" id="notif" style="cursor: pointer"
								title="Notifications" />

						</div>

						<div class="ui-g-12 ui-md-6 ui-lg-2">
							<i class="fa fa-bars" id="view" style="cursor: pointer"
								title="Views" />

						</div>

						<div class="ui-g-12 ui-md-6 ui-lg-6">
							<p:menuButton value="admin" icon="fa fa-user"
								style="width:100%; font-size:10pt">
								<p:menuitem value="Setting" style="font-size:10pt" />
								<p:menuitem value="Manage YAVA" style="font-size:10pt" />
								<p:menuitem value="About" style="font-size:10pt" />
								<p:separator />
								<p:menuitem value="Sign Out" style="font-size:10pt" />
							</p:menuButton>
						</div>
					</div>
				</f:facet>
				<p:breadCrumb style="font-size:10pt">
					<p:menuitem value="Breadcrumb" />
					<p:menuitem value="Services" />
					<p:menuitem value="Sqoop" />
					<p:menuitem value="Configs" />
				</p:breadCrumb>
				<p:accordionPanel>

					<p:tab title="sqoop-env">


						<p:dataTable var="entry"
							value="#{sqoopView.getProperties('sqoop-env')}">
							<p:column>
								<h:outputText value="#{entry.key}" />
							</p:column>
							<p:column>
								<h:outputText value="#{entry.value}" />
							</p:column>
						</p:dataTable>

					</p:tab>


					<p:tab title="sqoop-site">


						<p:dataTable var="entry"
							value="#{sqoopView.getProperties('sqoop-site')}">
							<p:column>
								<h:outputText value="#{entry.key}" />
							</p:column>
							<p:column>
								<h:outputText value="#{entry.value}" />
							</p:column>
						</p:dataTable>

					</p:tab>

					<p:tab title="sqoop-site">


						<p:dataTable var="entry"
							value="#{sqoopView.getProperties('sqoop-atlas-application.properties')}">
							<p:column>
								<h:outputText value="#{entry.key}" />
							</p:column>
							<p:column>
								<h:outputText value="#{entry.value}" />
							</p:column>
						</p:dataTable>

					</p:tab>

				</p:accordionPanel>
			</p:tab>

		</p:tabView>
	</h:form>

</ui:composition>